defaults:
  - //datasets/work/hb-mlaifsp-mm/work/repositories/cxrmate/config/test_huggingface/longitudinal_gen_prompt_cxr-bert.yaml@_global_
  - _self_

exp_dir: /datasets/work/hb-mlaifsp-mm/work/experiments
dataset_dir: /scratch3/nic261/datasets  # Place MIMIC-CXR in this directory.
ckpt_zoo_dir: /datasets/work/hb-mlaifsp-mm/work/checkpoints
