defaults:
  - single_tf
  - _self_

module: modules.lightning_modules.longitudinal.scst.gt_prompt
definition: GTPromptCXRBERT

mbatch_size: 2

variable_ckpt_name: None

warm_start_name: 'aehrc/cxrmate-tf'

lr: 5e-6

max_epochs: 1
