defaults:
  - single_tf
  - _self_

module: modules.lightning_modules.longitudinal.scst.gt_prompt
definition: GTPromptCXRBERT

mbatch_size: 2

multi_ckpt_name: null

warm_start_name: 'aehrc/cxrmate-tf'

lr: 5e-6

max_epochs: 1
val_check_interval: 0.1
