defaults:
  - single_tf
  - _self_

module: modules.lightning_modules.longitudinal.gt_prompt
definition: GTPrompt

mbatch_size: 2

multi_ckpt_name: 'aehrc/cxrmate-multi-tf'  # To warm-start the encoder-to-decoder model.
