defaults:
  - single_tf
  - _self_

module: modules.lightning_modules.longitudinal.scst.gen_prompt
definition: GeneratedPromptCXRBERT

mbatch_size: 1

multi_ckpt_name: null

warm_start_name: 'aehrc/cxrmate-tf'

lr: 5e-6

max_epochs: 1
