defaults:
  - 083_any_variable
  - ancillary/1gpu@_global_
  # - ancillary/4gpu@_global_
  # - ancillary/2hr@_global_
  - ancillary/24hr@_global_
  - _self_

module: task.mimic_cxr.model.report_gen.all.variable
definition: VariableCXRAll
