defaults:
  - 082_any_single
  - ancillary/1gpu@_global_
  # - ancillary/4gpu@_global_
  - ancillary/2hr@_global_
  # - ancillary/24hr@_global_
  - _self_

# limit_test_batches: 0.1

module: task.mimic_cxr.model.report_gen.all.prompt
definition: GTPromptAll

mbatch_size: 2
  