defaults:
  - 082_any_single
  - ancillary/1gpu@_global_
  # - ancillary/4gpu@_global_
  - ancillary/2hr@_global_
  # - ancillary/24hr@_global_
  - _self_

module: task.mimic_cxr.model.report_gen.any.gen_prompt
definition: GeneratedPrompt

mbatch_size: 1

other_exp_dir: /datasets/work/hb-mlaifsp-mm/work/experiments/mimic_cxr/081_any_prompt
other_monitor: val_report_chexbert_f1_macro
other_monitor_mode: max
