defaults:
  - 082_any_single
  - ancillary/1gpu@_global_
  # - ancillary/2gpu@_global_
  # - ancillary/4gpu@_global_
  # - ancillary/2hr@_global_
  # - ancillary/24hr@_global_
  - _self_

# time_limit: '166:00:00'

# Debug:
# limit_train_batches: 0.0001

module: task.mimic_cxr.model.report_gen.any.scst.gen_prompt
definition: CXRBERT

mbatch_size: 1

lr: 5e-6

warm_start_exp_dir: /datasets/work/hb-mlaifsp-mm/work/experiments/mimic_cxr/081_any_prompt
warm_start_monitor: val_report_chexbert_f1_macro
warm_start_monitor_mode: max

max_epochs: 1
enable_progress_bar: True
log_every_n_steps: 50
val_check_interval: 0.1
