defaults:
  - 082_any_single
  - ancillary/1gpu@_global_
  # - ancillary/4gpu@_global_
  - ancillary/2hr@_global_
  # - ancillary/24hr@_global_
  - _self_

lr: 1e-4
module: task.mimic_cxr.model.report_gen.any.prompt_variable_lora
definition: GTPromptLoRA

mbatch_size: 2

variable_ckpt_path: /datasets/work/hb-mlaifsp-mm/work/experiments/mimic_cxr/083_any_variable/trial_1/epoch=28-val_report_chexbert_f1_macro=0.383505.ckpt
