defaults:
  - 082_any_single
  - ancillary/1gpu@_global_
  - ancillary/2hr@_global_
  - _self_

module: task.mimic_cxr.model.report_gen.any.prompt_variable_lora
definition: GeneratedPrompt

mbatch_size: 1

variable_ckpt_path: /datasets/work/hb-mlaifsp-mm/work/experiments/mimic_cxr/083_any_variable/trial_1/epoch=28-val_report_chexbert_f1_macro=0.383505.ckpt

other_exp_dir: /datasets/work/hb-mlaifsp-mm/work/experiments/mimic_cxr/091_any_prompt_variable_lora
other_monitor: val_report_chexbert_f1_macro
other_monitor_mode: max
