time_limit: '02:00:00'
memory: '64GB'
email: 'aaron.nicolson@csiro.au'

exp_dir: /datasets/work/hb-mlaifsp-mm/work/experiments
dataset_dir: /datasets/work/hb-mlaifsp-mm/work/datasets
ckpt_zoo_dir: /datasets/work/hb-mlaifsp-mm/work/checkpoints
venv_path: /datasets/work/hb-mlaifsp-mm/work/environments/multimodal_23/bin/activate
cluster_manager_commands: [['account', 'OD-221833']]

devices: 1
num_nodes: 1
num_workers: 5
strategy: 'ddp'  # Training using 4GPUs w. DDP, hence debug with 1GPU w. DDP.


test_ckpt_path: /datasets/work/hb-mlaifsp-mm/work/experiments/mimic_cxr/082_any_single/trial_0/epoch=25-val_report_chexbert_f1_macro=0.309503.ckpt

module: modules.lightning_modules.single
definition: SingleCXR

sections_to_evaluate: ['report']
# generation_config: 
#   min_new_tokens: 5

max_images_per_study: 5
lr: 5e-5
max_epochs: 32
mbatch_size: 2
accumulated_mbatch_size: 32
every_n_epochs: 1
monitor: 'val_report_chexbert_f1_macro'
monitor_mode: 'max'
precision: 16
deterministic: False
decoder_max_len: 256
num_test_beams: 4
enable_progress_bar: True
weights_summary: 'full'

fact_entnli_mbatch_size: 1

image_dir:  /datasets/work/hb-mlaifsp-mm/work/images
module_load_apptainer: module load apptainer/1.1.3;
